### ISSUE TITLE
Docker compose issue

### ISSUE THREAD

**Issue by MatousEibich** [neo4j-labs/llm-graph-builder#279] opened 2024-05-06 07:27 UTC
Hello! I saw the demo video but I've run into multiple issues when trying to run docker compose.

First, I struggled w NPM_TOKEN. 

 => ERROR [frontend build 4/7] RUN yarn add @neo4j-nvl/interaction-handlers @neo4j-nvl/core @neo4j-nvl/react       0.5s
------
 > [frontend build 4/7] RUN yarn add @neo4j-nvl/interaction-handlers @neo4j-nvl/core @neo4j-nvl/react:
0.453 yarn add v1.22.19
0.482 error An unexpected error occurred: "Failed to replace env in config: ${NPM_TOKEN}".
0.482 info If you think this is a bug, please open a bug report with the information provided in "/app/yarn-error.log".
0.482 info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.`

I needed to do couple of workarounds and eventually ended w placing NPM_TOKEN directly into frontend Docker file. 

Then, second error came up:

` => ERROR [frontend build 5/8] RUN yarn add @neo4j-nvl/interaction-handlers @neo4j-nvl/core @neo4j-nvl/react       4.2s
------
 > [frontend build 5/8] RUN yarn add @neo4j-nvl/interaction-handlers @neo4j-nvl/core @neo4j-nvl/react:
1.045 yarn add v1.22.19
1.262 [1/4] Resolving packages...
4.071 error An unexpected error occurred: "https://registry.yarnpkg.com/@neo4j-nvl%2finteraction-handlers: Not found".
4.071 info If you think this is a bug, please open a bug report with the information provided in "/app/yarn-error.log".
4.071 info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
------
failed to solve: process "/bin/sh -c yarn add @neo4j-nvl/interaction-handlers @neo4j-nvl/core @neo4j-nvl/react" did not complete successfully: exit code: 1`

I've not managed to solve this one. GPT-4 told me to go through npm registry and look for these packages but I have not found them. I've got 0 experience with front end so this is kind of hard for me to debug. 

I feel like the README could be a bit more instructive, getting started w this has been a headache so far. From the comments section under the demo video I can see that I'm not the only one struggling. I really like the idea and loved the demo, so I want to get this to work. :)

**Comment by MatousEibich** [comment] 2024-05-06 07:39
Seems similar to issue #261

**Comment by msenechal** [comment] 2024-05-06 07:42
Hi @MatousEibich ,
Yes, this is the same issue, neo4j-nvl is the private package I was referring to,
This lib for the graph visualization should become public soon, in the meantime, I provided [a small fix here](https://github.com/msenechal/llm-graph-builder/tree/tmp/issue-261)

Which essentially:
- Remove the private package
- Remove the graph visualisation in the GraphView component and replace it with a tmp text

**Comment by msenechal** [comment] 2024-05-13 08:39
@prakriti-solankey @karanchellani can we close this one? duplicate of #261

**Closed** 2024-05-14 05:33 UTC
