### ISSUE TITLE
docker-compose up --build failed due to missing nvl package on npm registry

### ISSUE THREAD

**Issue by cklam12345** [neo4j-labs/llm-graph-builder#255] opened 2024-04-28 16:29 UTC
=> ERROR [frontend build 4/7] RUN yarn add @neo4j-nvl/interaction-handlers @neo4j-nvl/core @neo4j-nvl/react                             0.3s
------
 > [frontend build 4/7] RUN yarn add @neo4j-nvl/interaction-handlers @neo4j-nvl/core @neo4j-nvl/react:
0.235 yarn add v1.22.19
0.252 error An unexpected error occurred: "Failed to replace env in config: ${NPM_TOKEN}".
0.252 info If you think this is a bug, please open a bug report with the information provided in "/app/yarn-error.log".
0.252 info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
------
failed to solve: process "/bin/sh -c yarn add @neo4j-nvl/interaction-handlers @neo4j-nvl/core @neo4j-nvl/react" did not complete successfully: exit code: 1

**Comment by kartikpersistent** [comment] 2024-05-02 12:41
Hi @cklam12345 nvl is a  private library, we can't expose it publicly we will update the README about it.

**Comment by nickknyc** [comment] 2024-05-02 13:47
please update

**Comment by kartikpersistent** [comment] 2024-05-03 14:09
it is going to be public soon

**Comment by msenechal** [comment] 2024-05-04 15:44
Since it is a duplicate of [this issue](https://github.com/neo4j-labs/llm-graph-builder/issues/261) maybe we can close this one and refer to issue #261 ?

**Comment by msenechal** [comment] 2024-05-06 07:43
for reference, here is my message on issue #261 
Hi all,
The lib for the graph visualization should become public soon, in the meantime, I provided [a small fix here](https://github.com/msenechal/llm-graph-builder/tree/tmp/issue-261)

Which essentially:
- Remove the private package
- Remove the graph visualisation in the GraphView component and replace it with a tmp text

**Comment by msenechal** [comment] 2024-05-13 08:41
@prakriti-solankey @karanchellani can we close this one? duplicate of #261

**Closed** 2024-05-14 05:34 UTC
